version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: ecommerce_postgres
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432" # Mapeia a porta 5432 interna do container para a 5433 da sua máquina (conforme seu .env)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: